// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: app/rpc/app.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelType int32

const (
	ModelType_CHAT      ModelType = 0
	ModelType_EMBEDDING ModelType = 1
)

// Enum value maps for ModelType.
var (
	ModelType_name = map[int32]string{
		0: "CHAT",
		1: "EMBEDDING",
	}
	ModelType_value = map[string]int32{
		"CHAT":      0,
		"EMBEDDING": 1,
	}
)

func (x ModelType) Enum() *ModelType {
	p := new(ModelType)
	*p = x
	return p
}

func (x ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_rpc_app_proto_enumTypes[0].Descriptor()
}

func (ModelType) Type() protoreflect.EnumType {
	return &file_app_rpc_app_proto_enumTypes[0]
}

func (x ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelType.Descriptor instead.
func (ModelType) EnumDescriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_app_rpc_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{0}
}

type AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Models        []*ModelRequirement    `protobuf:"bytes,4,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_app_rpc_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppInfo) GetModels() []*ModelRequirement {
	if x != nil {
		return x.Models
	}
	return nil
}

type ModelRequirement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            ModelType              `protobuf:"varint,2,opt,name=type,proto3,enum=mass.app.ModelType" json:"type,omitempty"`
	ChatConfig      *ChatModelConfig       `protobuf:"bytes,3,opt,name=chat_config,json=chatConfig,proto3" json:"chat_config,omitempty"`
	EmbeddingConfig *EmbeddingModelConfig  `protobuf:"bytes,4,opt,name=embedding_config,json=embeddingConfig,proto3" json:"embedding_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModelRequirement) Reset() {
	*x = ModelRequirement{}
	mi := &file_app_rpc_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequirement) ProtoMessage() {}

func (x *ModelRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequirement.ProtoReflect.Descriptor instead.
func (*ModelRequirement) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{2}
}

func (x *ModelRequirement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelRequirement) GetType() ModelType {
	if x != nil {
		return x.Type
	}
	return ModelType_CHAT
}

func (x *ModelRequirement) GetChatConfig() *ChatModelConfig {
	if x != nil {
		return x.ChatConfig
	}
	return nil
}

func (x *ModelRequirement) GetEmbeddingConfig() *EmbeddingModelConfig {
	if x != nil {
		return x.EmbeddingConfig
	}
	return nil
}

type ChatModelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContextSize   int32                  `protobuf:"varint,2,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Threads       int32                  `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,5,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	FlashAttn     string                 `protobuf:"bytes,7,opt,name=flash_attn,json=flashAttn,proto3" json:"flash_attn,omitempty"`
	GpuLayers     int32                  `protobuf:"varint,8,opt,name=gpu_layers,json=gpuLayers,proto3" json:"gpu_layers,omitempty"`
	MainGpu       string                 `protobuf:"bytes,9,opt,name=main_gpu,json=mainGpu,proto3" json:"main_gpu,omitempty"`
	TensorSplit   string                 `protobuf:"bytes,10,opt,name=tensor_split,json=tensorSplit,proto3" json:"tensor_split,omitempty"`
	Thinking      bool                   `protobuf:"varint,11,opt,name=thinking,proto3" json:"thinking,omitempty"`
	MmprojPath    string                 `protobuf:"bytes,12,opt,name=mmproj_path,json=mmprojPath,proto3" json:"mmproj_path,omitempty"` // Vision projector GGUF path (enables vision/multimodal)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatModelConfig) Reset() {
	*x = ChatModelConfig{}
	mi := &file_app_rpc_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatModelConfig) ProtoMessage() {}

func (x *ChatModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatModelConfig.ProtoReflect.Descriptor instead.
func (*ChatModelConfig) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{3}
}

func (x *ChatModelConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChatModelConfig) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *ChatModelConfig) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ChatModelConfig) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ChatModelConfig) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *ChatModelConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatModelConfig) GetFlashAttn() string {
	if x != nil {
		return x.FlashAttn
	}
	return ""
}

func (x *ChatModelConfig) GetGpuLayers() int32 {
	if x != nil {
		return x.GpuLayers
	}
	return 0
}

func (x *ChatModelConfig) GetMainGpu() string {
	if x != nil {
		return x.MainGpu
	}
	return ""
}

func (x *ChatModelConfig) GetTensorSplit() string {
	if x != nil {
		return x.TensorSplit
	}
	return ""
}

func (x *ChatModelConfig) GetThinking() bool {
	if x != nil {
		return x.Thinking
	}
	return false
}

func (x *ChatModelConfig) GetMmprojPath() string {
	if x != nil {
		return x.MmprojPath
	}
	return ""
}

type EmbeddingModelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContextSize   int32                  `protobuf:"varint,2,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	GpuLayers     int32                  `protobuf:"varint,5,opt,name=gpu_layers,json=gpuLayers,proto3" json:"gpu_layers,omitempty"`
	MainGpu       string                 `protobuf:"bytes,6,opt,name=main_gpu,json=mainGpu,proto3" json:"main_gpu,omitempty"`
	TensorSplit   string                 `protobuf:"bytes,7,opt,name=tensor_split,json=tensorSplit,proto3" json:"tensor_split,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingModelConfig) Reset() {
	*x = EmbeddingModelConfig{}
	mi := &file_app_rpc_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingModelConfig) ProtoMessage() {}

func (x *EmbeddingModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingModelConfig.ProtoReflect.Descriptor instead.
func (*EmbeddingModelConfig) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingModelConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EmbeddingModelConfig) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *EmbeddingModelConfig) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *EmbeddingModelConfig) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *EmbeddingModelConfig) GetGpuLayers() int32 {
	if x != nil {
		return x.GpuLayers
	}
	return 0
}

func (x *EmbeddingModelConfig) GetMainGpu() string {
	if x != nil {
		return x.MainGpu
	}
	return ""
}

func (x *EmbeddingModelConfig) GetTensorSplit() string {
	if x != nil {
		return x.TensorSplit
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_app_rpc_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_app_rpc_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HandleRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequestRequest) Reset() {
	*x = HandleRequestRequest{}
	mi := &file_app_rpc_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequestRequest) ProtoMessage() {}

func (x *HandleRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleRequestRequest) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{7}
}

func (x *HandleRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HandleRequestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HandleRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequestResponse) Reset() {
	*x = HandleRequestResponse{}
	mi := &file_app_rpc_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequestResponse) ProtoMessage() {}

func (x *HandleRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequestResponse.ProtoReflect.Descriptor instead.
func (*HandleRequestResponse) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{8}
}

func (x *HandleRequestResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HandleRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandleRequestResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// HandleRequestStreamChunk is one frame of a streaming response. The terminal
// frame either has done=true (clean end) or a non-empty error.
type HandleRequestStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequestStreamChunk) Reset() {
	*x = HandleRequestStreamChunk{}
	mi := &file_app_rpc_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequestStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequestStreamChunk) ProtoMessage() {}

func (x *HandleRequestStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequestStreamChunk.ProtoReflect.Descriptor instead.
func (*HandleRequestStreamChunk) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{9}
}

func (x *HandleRequestStreamChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HandleRequestStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *HandleRequestStreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandleRequestStreamChunk) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SetLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`   // zerolog level name: "trace","debug","info","warn","error"
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "console" or "json" (empty = no change)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	mi := &file_app_rpc_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{10}
}

func (x *SetLogLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SetLogLevelRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SetLogLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelResponse) Reset() {
	*x = SetLogLevelResponse{}
	mi := &file_app_rpc_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelResponse) ProtoMessage() {}

func (x *SetLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelResponse.ProtoReflect.Descriptor instead.
func (*SetLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_app_rpc_app_proto_rawDescGZIP(), []int{11}
}

var File_app_rpc_app_proto protoreflect.FileDescriptor

const file_app_rpc_app_proto_rawDesc = "" +
	"\n" +
	"\x11app/rpc/app.proto\x12\bmass.app\"\x10\n" +
	"\x0eGetInfoRequest\"\x8d\x01\n" +
	"\aAppInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x06models\x18\x04 \x03(\v2\x1a.mass.app.ModelRequirementR\x06models\"\xd6\x01\n" +
	"\x10ModelRequirement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.mass.app.ModelTypeR\x04type\x12:\n" +
	"\vchat_config\x18\x03 \x01(\v2\x19.mass.app.ChatModelConfigR\n" +
	"chatConfig\x12I\n" +
	"\x10embedding_config\x18\x04 \x01(\v2\x1e.mass.app.EmbeddingModelConfigR\x0fembeddingConfig\"\x80\x03\n" +
	"\x0fChatModelConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontext_size\x18\x02 \x01(\x05R\vcontextSize\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x18\n" +
	"\athreads\x18\x04 \x01(\x05R\athreads\x12%\n" +
	"\x0emax_concurrent\x18\x05 \x01(\x05R\rmaxConcurrent\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"flash_attn\x18\a \x01(\tR\tflashAttn\x12\x1d\n" +
	"\n" +
	"gpu_layers\x18\b \x01(\x05R\tgpuLayers\x12\x19\n" +
	"\bmain_gpu\x18\t \x01(\tR\amainGpu\x12!\n" +
	"\ftensor_split\x18\n" +
	" \x01(\tR\vtensorSplit\x12\x1a\n" +
	"\bthinking\x18\v \x01(\bR\bthinking\x12\x1f\n" +
	"\vmmproj_path\x18\f \x01(\tR\n" +
	"mmprojPath\"\xeb\x01\n" +
	"\x14EmbeddingModelConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontext_size\x18\x02 \x01(\x05R\vcontextSize\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12%\n" +
	"\x0emax_concurrent\x18\x04 \x01(\x05R\rmaxConcurrent\x12\x1d\n" +
	"\n" +
	"gpu_layers\x18\x05 \x01(\x05R\tgpuLayers\x12\x19\n" +
	"\bmain_gpu\x18\x06 \x01(\tR\amainGpu\x12!\n" +
	"\ftensor_split\x18\a \x01(\tR\vtensorSplit\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"N\n" +
	"\x14HandleRequestRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadJ\x04\b\x03\x10\x04\"f\n" +
	"\x15HandleRequestResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"}\n" +
	"\x18HandleRequestStreamChunk\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"B\n" +
	"\x12SetLogLevelRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x15\n" +
	"\x13SetLogLevelResponse*$\n" +
	"\tModelType\x12\b\n" +
	"\x04CHAT\x10\x00\x12\r\n" +
	"\tEMBEDDING\x10\x012\xff\x02\n" +
	"\x03App\x128\n" +
	"\aGetInfo\x12\x18.mass.app.GetInfoRequest\x1a\x11.mass.app.AppInfo\"\x00\x12=\n" +
	"\x06Health\x12\x17.mass.app.HealthRequest\x1a\x18.mass.app.HealthResponse\"\x00\x12R\n" +
	"\rHandleRequest\x12\x1e.mass.app.HandleRequestRequest\x1a\x1f.mass.app.HandleRequestResponse\"\x00\x12]\n" +
	"\x13HandleRequestStream\x12\x1e.mass.app.HandleRequestRequest\x1a\".mass.app.HandleRequestStreamChunk\"\x000\x01\x12L\n" +
	"\vSetLogLevel\x12\x1c.mass.app.SetLogLevelRequest\x1a\x1d.mass.app.SetLogLevelResponse\"\x00B4Z2github.com/chinese-room-solutions/mass-sdk/app/rpcb\x06proto3"

var (
	file_app_rpc_app_proto_rawDescOnce sync.Once
	file_app_rpc_app_proto_rawDescData []byte
)

func file_app_rpc_app_proto_rawDescGZIP() []byte {
	file_app_rpc_app_proto_rawDescOnce.Do(func() {
		file_app_rpc_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_rpc_app_proto_rawDesc), len(file_app_rpc_app_proto_rawDesc)))
	})
	return file_app_rpc_app_proto_rawDescData
}

var file_app_rpc_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_rpc_app_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_rpc_app_proto_goTypes = []any{
	(ModelType)(0),                   // 0: mass.app.ModelType
	(*GetInfoRequest)(nil),           // 1: mass.app.GetInfoRequest
	(*AppInfo)(nil),                  // 2: mass.app.AppInfo
	(*ModelRequirement)(nil),         // 3: mass.app.ModelRequirement
	(*ChatModelConfig)(nil),          // 4: mass.app.ChatModelConfig
	(*EmbeddingModelConfig)(nil),     // 5: mass.app.EmbeddingModelConfig
	(*HealthRequest)(nil),            // 6: mass.app.HealthRequest
	(*HealthResponse)(nil),           // 7: mass.app.HealthResponse
	(*HandleRequestRequest)(nil),     // 8: mass.app.HandleRequestRequest
	(*HandleRequestResponse)(nil),    // 9: mass.app.HandleRequestResponse
	(*HandleRequestStreamChunk)(nil), // 10: mass.app.HandleRequestStreamChunk
	(*SetLogLevelRequest)(nil),       // 11: mass.app.SetLogLevelRequest
	(*SetLogLevelResponse)(nil),      // 12: mass.app.SetLogLevelResponse
}
var file_app_rpc_app_proto_depIdxs = []int32{
	3,  // 0: mass.app.AppInfo.models:type_name -> mass.app.ModelRequirement
	0,  // 1: mass.app.ModelRequirement.type:type_name -> mass.app.ModelType
	4,  // 2: mass.app.ModelRequirement.chat_config:type_name -> mass.app.ChatModelConfig
	5,  // 3: mass.app.ModelRequirement.embedding_config:type_name -> mass.app.EmbeddingModelConfig
	1,  // 4: mass.app.App.GetInfo:input_type -> mass.app.GetInfoRequest
	6,  // 5: mass.app.App.Health:input_type -> mass.app.HealthRequest
	8,  // 6: mass.app.App.HandleRequest:input_type -> mass.app.HandleRequestRequest
	8,  // 7: mass.app.App.HandleRequestStream:input_type -> mass.app.HandleRequestRequest
	11, // 8: mass.app.App.SetLogLevel:input_type -> mass.app.SetLogLevelRequest
	2,  // 9: mass.app.App.GetInfo:output_type -> mass.app.AppInfo
	7,  // 10: mass.app.App.Health:output_type -> mass.app.HealthResponse
	9,  // 11: mass.app.App.HandleRequest:output_type -> mass.app.HandleRequestResponse
	10, // 12: mass.app.App.HandleRequestStream:output_type -> mass.app.HandleRequestStreamChunk
	12, // 13: mass.app.App.SetLogLevel:output_type -> mass.app.SetLogLevelResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_rpc_app_proto_init() }
func file_app_rpc_app_proto_init() {
	if File_app_rpc_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_rpc_app_proto_rawDesc), len(file_app_rpc_app_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_app_proto_goTypes,
		DependencyIndexes: file_app_rpc_app_proto_depIdxs,
		EnumInfos:         file_app_rpc_app_proto_enumTypes,
		MessageInfos:      file_app_rpc_app_proto_msgTypes,
	}.Build()
	File_app_rpc_app_proto = out.File
	file_app_rpc_app_proto_goTypes = nil
	file_app_rpc_app_proto_depIdxs = nil
}
