// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: app/rpc/app.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	App_GetInfo_FullMethodName             = "/mass.app.App/GetInfo"
	App_Health_FullMethodName              = "/mass.app.App/Health"
	App_HandleRequest_FullMethodName       = "/mass.app.App/HandleRequest"
	App_HandleRequestStream_FullMethodName = "/mass.app.App/HandleRequestStream"
	App_SetLogLevel_FullMethodName         = "/mass.app.App/SetLogLevel"
)

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// App is implemented by apps and called by the MASS host.
type AppClient interface {
	// GetInfo returns app metadata and model requirements.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*AppInfo, error)
	// Health returns whether the app is healthy.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// HandleRequest dispatches an app-specific RPC.
	// The app calls MASS over HTTP (MASS_API_URL) as needed and returns JSON.
	HandleRequest(ctx context.Context, in *HandleRequestRequest, opts ...grpc.CallOption) (*HandleRequestResponse, error)
	// HandleRequestStream dispatches an app-specific streaming RPC.
	// Each message in the response stream is one chunk delivered to the caller
	// as an SSE event by MASS.
	HandleRequestStream(ctx context.Context, in *HandleRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandleRequestStreamChunk], error)
	// SetLogLevel changes the app's log verbosity at runtime.
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*AppInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppInfo)
	err := c.cc.Invoke(ctx, App_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, App_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) HandleRequest(ctx context.Context, in *HandleRequestRequest, opts ...grpc.CallOption) (*HandleRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleRequestResponse)
	err := c.cc.Invoke(ctx, App_HandleRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) HandleRequestStream(ctx context.Context, in *HandleRequestRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandleRequestStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &App_ServiceDesc.Streams[0], App_HandleRequestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandleRequestRequest, HandleRequestStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type App_HandleRequestStreamClient = grpc.ServerStreamingClient[HandleRequestStreamChunk]

func (c *appClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, App_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
// All implementations must embed UnimplementedAppServer
// for forward compatibility.
//
// App is implemented by apps and called by the MASS host.
type AppServer interface {
	// GetInfo returns app metadata and model requirements.
	GetInfo(context.Context, *GetInfoRequest) (*AppInfo, error)
	// Health returns whether the app is healthy.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// HandleRequest dispatches an app-specific RPC.
	// The app calls MASS over HTTP (MASS_API_URL) as needed and returns JSON.
	HandleRequest(context.Context, *HandleRequestRequest) (*HandleRequestResponse, error)
	// HandleRequestStream dispatches an app-specific streaming RPC.
	// Each message in the response stream is one chunk delivered to the caller
	// as an SSE event by MASS.
	HandleRequestStream(*HandleRequestRequest, grpc.ServerStreamingServer[HandleRequestStreamChunk]) error
	// SetLogLevel changes the app's log verbosity at runtime.
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	mustEmbedUnimplementedAppServer()
}

// UnimplementedAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServer struct{}

func (UnimplementedAppServer) GetInfo(context.Context, *GetInfoRequest) (*AppInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedAppServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAppServer) HandleRequest(context.Context, *HandleRequestRequest) (*HandleRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedAppServer) HandleRequestStream(*HandleRequestRequest, grpc.ServerStreamingServer[HandleRequestStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method HandleRequestStream not implemented")
}
func (UnimplementedAppServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedAppServer) mustEmbedUnimplementedAppServer() {}
func (UnimplementedAppServer) testEmbeddedByValue()             {}

// UnsafeAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServer will
// result in compilation errors.
type UnsafeAppServer interface {
	mustEmbedUnimplementedAppServer()
}

func RegisterAppServer(s grpc.ServiceRegistrar, srv AppServer) {
	// If the following call panics, it indicates UnimplementedAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&App_ServiceDesc, srv)
}

func _App_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_HandleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).HandleRequest(ctx, req.(*HandleRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_HandleRequestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HandleRequestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppServer).HandleRequestStream(m, &grpc.GenericServerStream[HandleRequestRequest, HandleRequestStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type App_HandleRequestStreamServer = grpc.ServerStreamingServer[HandleRequestStreamChunk]

func _App_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// App_ServiceDesc is the grpc.ServiceDesc for App service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var App_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mass.app.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _App_GetInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _App_Health_Handler,
		},
		{
			MethodName: "HandleRequest",
			Handler:    _App_HandleRequest_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _App_SetLogLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleRequestStream",
			Handler:       _App_HandleRequestStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/rpc/app.proto",
}
